"""drop_task_max_seconds

Revision ID: 154dd95dbcca
Revises: e90178677d91
Create Date: 2026-06-26 23:45:25.221364

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "154dd95dbcca"
down_revision: str | None = "e90178677d91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "max_seconds")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("max_seconds", sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
