"""drop_workspace_initialization_strategy

Revision ID: 2093601ab8c4
Revises: 154dd95dbcca
Create Date: 2026-06-27 06:52:35.138523

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2093601ab8c4"
down_revision: str | None = "154dd95dbcca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "initialization_strategy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("initialization_strategy", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
