"""initial schema

Revision ID: 4ddee12c1e07
Revises:
Create Date: 2026-06-26 15:05:03.486524

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ddee12c1e07"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("organization_reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_git_repo_url", sa.String(), nullable=True),
        sa.Column("is_path_accessible", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("workspace_setup_command", sa.String(), nullable=True),
        sa.Column("naming_pattern", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_table(
        "task",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("organization_reference", sa.String(), nullable=False),
        sa.Column("user_reference", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("current_state", sa.JSON(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("is_deleting", sa.Integer(), nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.object_id"], name="foreign_key_project_id"),
        sa.PrimaryKeyConstraint("object_id"),
        info={"monotonic_columns": frozenset({"is_deleted", "is_deleting"})},
    )
    op.create_table(
        "workspace",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("organization_reference", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("source_branch", sa.String(), nullable=True),
        sa.Column("target_branch", sa.String(), nullable=True),
        sa.Column("environment_id", sa.String(), nullable=True),
        sa.Column("source_git_hash", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Integer(), nullable=False),
        sa.Column("setup_status", sa.String(), nullable=False),
        sa.Column("setup_run_id", sa.String(), nullable=True),
        sa.Column("setup_command", sa.String(), nullable=True),
        sa.Column("setup_exit_code", sa.Integer(), nullable=True),
        sa.Column("setup_started_at", sa.Float(), nullable=True),
        sa.Column("setup_finished_at", sa.Float(), nullable=True),
        sa.Column("setup_log_path", sa.String(), nullable=True),
        sa.Column("setup_log_truncated", sa.Integer(), nullable=False),
        sa.Column("diff_status", sa.String(), nullable=False),
        sa.Column("diff_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_branch_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.object_id"], name="foreign_key_workspace_project_id"),
        sa.PrimaryKeyConstraint("object_id"),
        info={"monotonic_columns": frozenset({"is_deleted"})},
    )
    op.create_table(
        "notification",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("user_reference", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("importance", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["task.object_id"], name="foreign_key_task_id"),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_table(
        "saved_agent_message",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.object_id"], name="foreign_key_task_id"),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_index(
        "ix_saved_agent_message_task_id_created_at", "saved_agent_message", ["task_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_saved_agent_message_task_id_created_at", table_name="saved_agent_message")
    op.drop_table("saved_agent_message")
    op.drop_table("notification")
    op.drop_table("workspace")
    op.drop_table("task")
    op.drop_table("project")
    # ### end Alembic commands ###
