"""add ci_babysitter_paused to workspace

Revision ID: d841f2b44413
Revises: 4ddee12c1e07
Create Date: 2026-07-02 15:07:10.601047

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d841f2b44413"
down_revision: str | None = "4ddee12c1e07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="0" (False) so existing workspace rows backfill to not-paused.
    op.add_column("workspace", sa.Column("ci_babysitter_paused", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "ci_babysitter_paused")
    # ### end Alembic commands ###
