"""drop_setup_command_triggered

Revision ID: e90178677d91
Revises: 4ddee12c1e07
Create Date: 2026-06-26 22:24:44.038217

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e90178677d91"
down_revision: str | None = "4ddee12c1e07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "setup_command_triggered")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("setup_command_triggered", sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
