#!/usr/bin/env python3
"""This build script contains various functions used to assemble the build
artifact of Sculptor.

By only building the wheels we need, we save from having to import all of the
sculptor repo.
"""

import json
from pathlib import Path

import typer
from builder import darwin

from sculptor.version import dev_git_sha
from sculptor.version import pep_440_to_semver
from sculptor.version import pyproject_version

app = typer.Typer(pretty_exceptions_enable=False)


@app.command("version")
def version() -> None:
    """Print the Sculptor version and Git SHA."""
    typer.echo(f"Sculptor v{pyproject_version()}")
    typer.echo(f"Git SHA:  {dev_git_sha()}")


@app.command("create-version-file")
def create_version_file() -> None:
    """Create a version file with the Sculptor version and Git SHA."""
    sculptor_version = pyproject_version()

    sha = dev_git_sha()
    with Path("sculptor/_version.py").open("w") as f:
        f.write(
            f'"""Sculptor v{sculptor_version} version file, autogenerated by the build process.\nDo not edit."""\n'
        )
        f.write(f"__version__ = '{sculptor_version}'\n")
        f.write(f"__git_sha__ = '{sha}'\n")


@app.command("sync-frontend-version")
def sync_frontend_version(
    reverse: bool = typer.Option(False, "--reverse", "-r", help="Reset frontend package.json version to 0.0.0"),
) -> None:
    """Sync frontend package.json version with sculptor pyproject.toml version, or reset to 0.0.0 with --reverse."""
    frontend_package_json_path = Path("frontend/package.json")

    if not frontend_package_json_path.exists():
        typer.secho(f"Frontend package.json not found at {frontend_package_json_path}", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    # Read current package.json
    with frontend_package_json_path.open("r") as f:
        package_data = json.load(f)

    # Determine target version
    old_version = package_data.get("version", "unknown")
    if reverse:
        target_version = "0.0.0"
        action = "Reset"
    else:
        target_version = pep_440_to_semver(pyproject_version())
        action = "Updated"

    package_data["version"] = target_version

    # Write back to package.json
    with frontend_package_json_path.open("w") as f:
        json.dump(package_data, f, indent=2)
        f.write("\n")  # Add final newline for consistency

    typer.secho(f"{action} frontend package.json version: {old_version} → {target_version}", fg=typer.colors.GREEN)


@app.command("validate-darwin-binary")
def validate_darwin_binary(
    binary_path: Path = typer.Argument(..., help="Path to the macOS binary to validate."),
    arch: str = typer.Argument(..., help="Architecture of the binary (e.g., x86_64, arm64)."),
) -> None:
    """Given a file within the macOs App Bundle, this performs various validations."""

    if not darwin.validate_binary(binary_path=binary_path, arch=arch):
        typer.secho(f"Validation failed for binary at {binary_path}", fg=typer.colors.RED)
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
