import type { KeybindingDefinition } from "./types.ts";

export const KEYBINDING_DEFINITIONS: ReadonlyArray<KeybindingDefinition> = [
  {
    id: "new_workspace",
    name: "New workspace",
    description: "Create a new workspace",
    category: "workspaces",
    defaultBinding: "Meta+T",
  },
  {
    id: "open_workspace",
    name: "Go to workspace",
    description: "Open the command palette on the workspace switcher",
    category: "workspaces",
    defaultBinding: "Meta+P",
  },
  {
    id: "close_workspace",
    name: "Close workspace",
    description: "Close the current workspace tab",
    category: "workspaces",
    defaultBinding: "Meta+W",
  },
  {
    id: "delete_workspace",
    name: "Delete workspace",
    description: "Delete the current workspace and all of its agents",
    category: "workspaces",
    defaultBinding: "Meta+Shift+W",
  },
  {
    id: "next_tab",
    name: "Next tab",
    description: "Switch to the next workspace tab",
    category: "workspaces",
    defaultBinding: "Meta+]",
  },
  {
    id: "previous_tab",
    name: "Previous tab",
    description: "Switch to the previous workspace tab",
    category: "workspaces",
    defaultBinding: "Meta+[",
  },
  {
    id: "find_in_file",
    name: "Find in file",
    description: "Open the in-file search bar in the diff viewer",
    category: "general",
    defaultBinding: "Meta+F",
  },
  {
    id: "command_palette",
    name: "Command palette",
    description: "Open the command palette to search and run commands",
    category: "general",
    defaultBinding: "Meta+K",
  },
  {
    id: "help",
    name: "Help",
    description: "Toggle the help dialog",
    category: "general",
    defaultBinding: "Meta+/",
  },
  {
    id: "home",
    name: "Home",
    description: "Open the home page",
    category: "navigation",
    defaultBinding: "Meta+.",
  },
  {
    id: "settings",
    name: "Settings",
    description: "Open the settings page",
    category: "general",
    defaultBinding: "Meta+,",
  },
  {
    id: "toggle_theme",
    name: "Toggle theme",
    description: "Switch between light and dark mode",
    category: "general",
    defaultBinding: "Meta+Shift+D",
  },
  {
    id: "focus_mode",
    name: "Focus mode",
    description: "Hide or restore all panels",
    category: "general",
    defaultBinding: "Meta+\\",
  },
  {
    id: "zen_mode",
    name: "Zen mode",
    description: "Maximize the workspace by hiding all panels and UI chrome",
    category: "general",
    defaultBinding: "Meta+Shift+\\",
  },
  {
    id: "toggle_left_panel",
    name: "Toggle left panel",
    description: "Show or hide the left sidebar",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowLeft",
  },
  {
    id: "toggle_bottom_panel",
    name: "Toggle bottom panel",
    description: "Show or hide the bottom panel",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowDown",
  },
  {
    id: "toggle_right_panel",
    name: "Toggle right panel",
    description: "Show or hide the right sidebar",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowRight",
  },
  {
    id: "previous_agent",
    name: "Previous agent",
    description: "Switch to the agent on the left",
    category: "workspaces",
    defaultBinding: "Meta+Shift+[",
  },
  {
    id: "next_agent",
    name: "Next agent",
    description: "Switch to the agent on the right",
    category: "workspaces",
    defaultBinding: "Meta+Shift+]",
  },
  {
    id: "new_agent",
    name: "New agent",
    description: "Create a new agent in the current workspace",
    category: "workspaces",
    defaultBinding: "Meta+Shift+T",
  },
  {
    id: "open_in_app",
    name: "Open in app",
    description: "Open the repo in the preferred external app",
    category: "general",
    defaultBinding: "Meta+O",
  },
  {
    id: "clear_terminal",
    name: "Clear terminal",
    description: "Wipe the active terminal's screen and scrollback (when the terminal is focused)",
    category: "terminal",
    defaultBinding: "Ctrl+L",
  },
];
