"""Shared conftest content for Playwright-based integration test directories.

Any test directory that uses Sculptor's Playwright fixtures should import
from this module in its conftest.py:

    from sculptor.testing.playwright_conftest import *  # noqa: F401, F403
"""

import os
import shutil
import tempfile
from collections.abc import Generator
from pathlib import Path

import pytest
from playwright.sync_api import expect

from sculptor.testing.frontend_utils import DEFAULT_TEST_LOCALE
from sculptor.testing.frontend_utils import DEFAULT_TEST_VIEWPORT
from sculptor.testing.resources import sculptor_instance_  # noqa: F401
from sculptor.testing.resources import sculptor_instance_factory_  # noqa: F401
from sculptor.testing.resources import test_repo_factory_  # noqa: F401

# True iff this pytest process is an xdist controller — set once in
# pytest_configure and read by pytest_runtest_logfinish (which has no access
# to ``config``). The controller has ``--numprocesses`` set; workers don't
# inherit it. ``--dist`` would be a more direct signal but xdist rewrites it
# from "no" to "load" inside its own pytest_cmdline_main hook, which fires
# AFTER pytest_configure — at configure time ``dist`` is still "no".
_IS_XDIST_CONTROLLER: bool = False


def pytest_configure(config: pytest.Config) -> None:
    global _IS_XDIST_CONTROLLER
    _IS_XDIST_CONTROLLER = bool(config.getoption("numprocesses", None))


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item: pytest.Item, call: pytest.CallInfo) -> Generator[None, pytest.TestReport, None]:  # noqa: E501
    """Stash the call-phase report on the test node.

    SculptorInstance._post_test reads ``request.node.report_call`` to decide
    whether to tear down and recreate the shared instance for the next test.
    """
    outcome = yield
    report = outcome.get_result()
    if report.when == "call":
        item.report_call = report


def pytest_collection_modifyitems(items: list[pytest.Item]) -> None:
    """Sort tests to avoid unnecessary shared-instance restarts between groups.

    Three buckets, in order:
    1. Factory tests — each spawns its own Sculptor instance, so they run
       first to avoid interrupting the shared instance mid-run.
    2. Electron shared-instance tests — grouped so the Electron instance
       stays alive across all electron tests without browser tests interleaving.
    3. Browser shared-instance tests — grouped last.

    This mirrors the xdist distribution: within a worker, tests are executed
    in the sorted order, so each group of tests shares one long-lived instance
    of the appropriate type rather than causing restarts.
    """
    factory_tests = []
    electron_tests = []
    browser_tests = []
    for item in items:
        if "sculptor_instance_factory_" in getattr(item, "fixturenames", ()):
            factory_tests.append(item)
        elif (
            item.get_closest_marker("electron") is not None
            or item.get_closest_marker("electron_custom_command") is not None
        ):
            electron_tests.append(item)
        else:
            browser_tests.append(item)
    items[:] = factory_tests + electron_tests + browser_tests


# Session budget guard lives in the root conftest.py (pytest_runtest_setup
# hook). It uses pytest.fail() rather than pytest.exit() because with xdist,
# pytest.exit() crashes the worker and the controller then blocks in
# execnet.safe_terminate() waiting for other workers that may be stuck in
# per-test timeouts.


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    # Factory tests (sculptor_instance_factory_) reach the Playwright page through
    # pytest-playwright's built-in `page` fixture, which honors this override.
    # The shared-instance browser path (resources.py _get_or_create_shared_instance)
    # bypasses this fixture and must pass DEFAULT_TEST_VIEWPORT and
    # DEFAULT_TEST_LOCALE explicitly to new_context() to stay in sync.
    return {**browser_context_args, "viewport": DEFAULT_TEST_VIEWPORT, "locale": DEFAULT_TEST_LOCALE}


# This fixture depends on playwright's `output_path` fixture, we use it to
# record our artifacts and that way they sit next to videos and screenshots
# generated by playwright.
#
# It is important that it runs after the playwright's internal
# `_artifacts_recorder` so that we can actually see the files written by
# playwright. To achieve that, we use autouse as it's executed first.
# doc: https://docs.pytest.org/en/stable/reference/fixtures.html#autouse-fixtures-are-executed-first-within-their-scope
# NOTE: this breaks if we have any autouse fixtures that also depend on playwright's `page`, `context`, or `browser`!
#
# The `output_path` fixture is only generating a path and does nothing else so
# pulling it in should have no side effects.
@pytest.fixture(scope="function", autouse=True)
def record_generated_files(output_path: str, record_property):
    yield

    output = Path(output_path)
    if not output.exists():
        return

    tests_cwd_path = Path.cwd()
    assert output.is_dir(), f"Expected output path to be a directory, got {output}"
    assert output.is_relative_to(tests_cwd_path), (
        f"Expected output path to be relative to {tests_cwd_path}, got {output}"
    )
    output = output.relative_to(tests_cwd_path)

    record_property("test_results_path", str(output) + "/")

    file_types = {
        "trace*.zip": "playwright_trace_path",  # hardcoded name coming from playwright's `_artifacts_recorder`
        "*.png": "image_path",
        "*.webm": "video_path",
    }
    for child in output.iterdir():
        if child.is_file():
            for pattern, file_type in file_types.items():
                if child.match(pattern):
                    record_property(f"{file_type}-{str(child.relative_to(output))}", str(child))
        elif child.is_dir():
            record_property(f"directory_path-{str(child.relative_to(output))}", str(child) + "/")


@pytest.fixture(autouse=True)
def configure_expect_timeout(is_updating_snapshots_: bool) -> None:
    if is_updating_snapshots_:
        expect.set_options(timeout=5 * 60 * 1000)
    else:
        expect.set_options(timeout=0.5 * 60 * 1000)


def pytest_runtest_logfinish(nodeid: str, location: tuple[str, int | None, str]) -> None:
    """Reclaim Playwright scratch space between tests on the same worker.

    pytest-playwright writes trace/video/screenshot scratch under
    ``$TMPDIR/playwright-artifacts-<random>/`` and moves on-failure
    artifacts to ``output_path`` (== ``test-results/<nodeid>/``) inside
    its own ``_artifacts_recorder`` fixture finalizer. This hook fires
    after every function-scoped finalizer for the test, so by the time
    we glob, the failure trace has already been copied out and the
    leftover scratch dir is safe to remove.

    Without this, one test's mid-flight trace can fill the worker disk
    (some CI sandboxes hit ENOSPC at ~7 tests in), and every subsequent
    ``Tracing.start`` on the same context cascades with
    "Tracing has been already started" because the prior trace never
    closed cleanly.

    Skipped under pytest-xdist on BOTH workers and the controller. Workers
    each own their own ``playwright-artifacts-<random>`` and only their own
    is safe to remove; the controller re-fires ``pytest_runtest_logfinish``
    for every worker report (xdist/dsession.py:317-324) and would otherwise
    rmtree sibling workers' in-flight scratch dirs, surfacing as
    ``Tracing.stop: ENOENT ... .trace`` followed by "Tracing has been
    already started" on every later test in that sibling — the same
    cascade we are trying to prevent. A non-xdist CI runner (one test per
    sandbox) still benefits from the cleanup, so this gate keeps the fix
    where it matters and avoids the friendly-fire on CI ``XDIST_WORKERS=7``
    runs and on local-xdist runs.
    """
    if os.environ.get("PYTEST_XDIST_WORKER") or _IS_XDIST_CONTROLLER:
        return
    tmp = Path(tempfile.gettempdir())
    for scratch in tmp.glob("playwright-artifacts-*"):
        shutil.rmtree(scratch, ignore_errors=True)
