"""Constants shared by the Sculptor project"""

from enum import StrEnum

# Should be in sync with sculptor.foundation.thread_utils.EXIT_CODE_IRRECOVERABLE_ERROR
SCULPTOR_EXIT_CODE_IRRECOVERABLE_ERROR = 3
SCULPTOR_EXIT_CODE_PARENT_DIED = 4
SCULPTOR_EXIT_CODE_COULD_NOT_ACQUIRE_LOCK = 5


class ElementIDs(StrEnum):
    """Specific tags added to frontend HTML that can be used to find specific elements."""

    # Home Page Elements
    # Task Starter
    TASK_STARTER = "TASK_STARTER"
    TASK_INPUT = "TASK_INPUT"
    TASK_NAME_INPUT = "TASK_NAME_INPUT"
    START_TASK_BUTTON = "START_TASK_BUTTON"
    BRANCH_SELECTOR = "BRANCH_SELECTOR"
    BRANCH_OPTION = "BRANCH_OPTION"
    MODE_SELECTOR = "MODE_SELECTOR"
    MODE_OPTION_IN_PLACE = "MODE_OPTION_IN_PLACE"
    MODE_OPTION_CLONE = "MODE_OPTION_CLONE"
    MODE_OPTION_WORKTREE = "MODE_OPTION_WORKTREE"
    MODE_OPTION_EXISTING = "MODE_OPTION_EXISTING"
    BRANCH_NAME_INPUT = "BRANCH_NAME_INPUT"
    BRANCH_NAME_COLLISION_ERROR = "BRANCH_NAME_COLLISION_ERROR"
    BRANCH_NAME_RESET_BUTTON = "BRANCH_NAME_RESET_BUTTON"
    WORKSPACE_SELECTOR = "WORKSPACE_SELECTOR"
    WORKSPACE_OPTION_NAME = "WORKSPACE_OPTION_NAME"
    HOME_PAGE_SYSTEM_PROMPT_OPEN_BUTTON = "HOME_PAGE_SYSTEM_PROMPT_OPEN_BUTTON"
    HOME_PAGE_SYSTEM_PROMPT_INPUT = "HOME_PAGE_SYSTEM_PROMPT_INPUT"
    HOME_PAGE_SYSTEM_PROMPT_SAVE_BUTTON = "HOME_PAGE_SYSTEM_PROMPT_SAVE_BUTTON"
    VERSION = "VERSION"
    VERSION_POPOVER_CONTENT = "VERSION_POPOVER_CONTENT"
    VERSION_POPOVER_TANSTACK_DEVTOOLS_SWITCH = "VERSION_POPOVER_TANSTACK_DEVTOOLS_SWITCH"
    TANSTACK_DEVTOOLS_PANEL_HOST = "TANSTACK_DEVTOOLS_PANEL_HOST"

    # Top Bar Elements
    TOP_BAR = "TOP_BAR"
    HOME_BUTTON = "HOME_BUTTON"
    HELP_BUTTON = "HELP_BUTTON"
    KEYBOARD_SHORTCUTS_DIALOG = "KEYBOARD_SHORTCUTS_DIALOG"

    # Sidebar Elements
    SETTINGS_BUTTON = "SETTINGS_BUTTON"

    # Project Selector
    PROJECT_SELECTOR = "PROJECT_SELECTOR"
    PROJECT_SELECT_ITEM = "PROJECT_SELECT_ITEM"
    OPEN_NEW_REPO_BUTTON = "OPEN_NEW_REPO_BUTTON"

    # Task List and Task Item
    TASK_LIST = "TASK_LIST"
    TASK_BUTTON = "TASK_BUTTON"

    # Chat Page Elements
    # Task Header
    WORKSPACE_BANNER = "WORKSPACE_BANNER"
    BRANCH_NAME = "BRANCH_NAME"
    TASK_MODE_BADGE = "TASK_MODE_BADGE"

    # Repo Path Dropdown
    REPO_PATH_DROPDOWN_TRIGGER = "REPO_PATH_DROPDOWN_TRIGGER"
    REPO_PATH_DROPDOWN_COPY_PATH = "REPO_PATH_DROPDOWN_COPY_PATH"
    REPO_PATH_DROPDOWN_APP_ITEM = "REPO_PATH_DROPDOWN_APP_ITEM"
    REPO_PATH_DROPDOWN_SHORTCUT_HINT = "REPO_PATH_DROPDOWN_SHORTCUT_HINT"
    REPO_PATH_DROPDOWN_ALERT_OK = "REPO_PATH_DROPDOWN_ALERT_OK"

    # Command Palette (replaces the legacy Search Modal; Cmd+K)
    COMMAND_PALETTE_OPEN_BUTTON = "COMMAND_PALETTE_OPEN_BUTTON"
    COMMAND_PALETTE = "COMMAND_PALETTE"
    COMMAND_PALETTE_INPUT = "COMMAND_PALETTE_INPUT"
    COMMAND_PALETTE_LIST = "COMMAND_PALETTE_LIST"
    COMMAND_PALETTE_ITEM = "COMMAND_PALETTE_ITEM"
    COMMAND_PALETTE_GROUP = "COMMAND_PALETTE_GROUP"
    COMMAND_PALETTE_EMPTY = "COMMAND_PALETTE_EMPTY"
    COMMAND_PALETTE_FOOTER = "COMMAND_PALETTE_FOOTER"
    COMMAND_PALETTE_PAGE_BREADCRUMB = "COMMAND_PALETTE_PAGE_BREADCRUMB"

    # Chat Search Bar (Cmd+F)
    CHAT_SEARCH_BAR = "CHAT_SEARCH_BAR"
    CHAT_SEARCH_INPUT = "CHAT_SEARCH_INPUT"
    CHAT_SEARCH_MATCH_COUNTER = "CHAT_SEARCH_MATCH_COUNTER"

    # Chat Panel
    CHAT_PANEL = "CHAT_PANEL"
    USER_MESSAGE = "USER_MESSAGE"
    ASSISTANT_MESSAGE = "ASSISTANT_MESSAGE"
    DELETE_QUEUED_MESSAGE_BUTTON = "DELETE_QUEUED_MESSAGE_BUTTON"
    QUEUED_MESSAGE_BAR = "QUEUED_MESSAGE_BAR"
    QUEUED_MESSAGE_SEND_BUTTON = "QUEUED_MESSAGE_SEND_BUTTON"
    QUEUED_MESSAGE_EDIT_BUTTON = "QUEUED_MESSAGE_EDIT_BUTTON"
    QUEUED_MESSAGE_CANCEL_BUTTON = "QUEUED_MESSAGE_CANCEL_BUTTON"
    UNDO_QUEUED_MESSAGE_DIALOG = "UNDO_QUEUED_MESSAGE_DIALOG"
    UNDO_QUEUED_MESSAGE_CANCEL_BUTTON = "UNDO_QUEUED_MESSAGE_CANCEL_BUTTON"
    UNDO_QUEUED_MESSAGE_COPY_BUTTON = "UNDO_QUEUED_MESSAGE_COPY_BUTTON"
    UNDO_QUEUED_MESSAGE_OVERWRITE_BUTTON = "UNDO_QUEUED_MESSAGE_OVERWRITE_BUTTON"
    ERROR_BLOCK = "ERROR_BLOCK"
    ERROR_BLOCK_RETRY_BUTTON = "ERROR_BLOCK_RETRY_BUTTON"
    ERROR_INPUT = "ERROR_INPUT"

    CHAT_INPUT = "CHAT_INPUT"
    SEND_BUTTON = "SEND_BUTTON"
    THINKING_INDICATOR = "THINKING_INDICATOR"
    MODEL_SELECTOR = "MODEL_SELECTOR"
    MODEL_OPTION = "MODEL_OPTION"
    CONTEXT_SUMMARY = "CONTEXT_SUMMARY"
    CONTEXT_SUMMARY_HEADER = "CONTEXT_SUMMARY_HEADER"
    RESUME_RESPONSE = "RESUME_RESPONSE"
    COMPACTION_BUTTON = "COMPACTION_BUTTON"
    COMPACTION_PANEL = "COMPACTION_PANEL"
    COMPACTION_BAR = "COMPACTION_BAR"

    # /btw popup
    BTW_POPUP = "BTW_POPUP"
    BTW_POPUP_DRAG_HANDLE = "BTW_POPUP_DRAG_HANDLE"
    BTW_POPUP_CLOSE_BUTTON = "BTW_POPUP_CLOSE_BUTTON"
    BTW_POPUP_QUESTION = "BTW_POPUP_QUESTION"
    BTW_POPUP_ANSWER = "BTW_POPUP_ANSWER"
    BTW_POPUP_STREAMING_INDICATOR = "BTW_POPUP_STREAMING_INDICATOR"

    # AskUserQuestion
    ASK_USER_QUESTION_PANEL = "ASK_USER_QUESTION_PANEL"
    ASK_USER_QUESTION_OPTION = "ASK_USER_QUESTION_OPTION"
    ASK_USER_QUESTION_OTHER_OPTION = "ASK_USER_QUESTION_OTHER_OPTION"
    ASK_USER_QUESTION_OTHER_INPUT = "ASK_USER_QUESTION_OTHER_INPUT"
    ASK_USER_QUESTION_NEXT_BUTTON = "ASK_USER_QUESTION_NEXT_BUTTON"
    ASK_USER_QUESTION_PREVIOUS_BUTTON = "ASK_USER_QUESTION_PREVIOUS_BUTTON"
    ASK_USER_QUESTION_SUBMIT = "ASK_USER_QUESTION_SUBMIT"
    ASK_USER_QUESTION_DISMISS_BUTTON = "ASK_USER_QUESTION_DISMISS_BUTTON"
    ASK_USER_QUESTION_TOOL_BLOCK = "ASK_USER_QUESTION_TOOL_BLOCK"
    ASK_USER_QUESTION_TEXT = "ASK_USER_QUESTION_TEXT"
    ASK_USER_QUESTION_ANSWER_TEXT = "ASK_USER_QUESTION_ANSWER_TEXT"
    ASK_USER_QUESTION_ANSWERED_OPTION = "ASK_USER_QUESTION_ANSWERED_OPTION"
    ASK_USER_QUESTION_CUSTOM_TEXT = "ASK_USER_QUESTION_CUSTOM_TEXT"

    # Plan Mode
    EXIT_PLAN_MODE_TOOL_BLOCK = "EXIT_PLAN_MODE_TOOL_BLOCK"
    PLAN_MODE_TOGGLE = "PLAN_MODE_TOGGLE"
    FAST_MODE_TOGGLE = "FAST_MODE_TOGGLE"
    EFFORT_SELECTOR = "EFFORT_SELECTOR"
    EFFORT_SELECTOR_OPTION = "EFFORT_SELECTOR_OPTION"

    # Capability-gated affordances rendered disabled-with-tooltip (the shared
    # CapabilityGate treatment) when the active task's harness lacks the
    # capability. One test hook per interactive surface that can host a disabled
    # state; surfaces that cannot (picker rows, the skills panel, the
    # model-gated fast-mode toggle) are suppressed and asserted absent instead.
    CAPABILITY_DISABLED_PLAN_MODE = "CAPABILITY_DISABLED_PLAN_MODE"
    CAPABILITY_DISABLED_STOP = "CAPABILITY_DISABLED_STOP"
    CAPABILITY_DISABLED_QUEUED_INTERRUPT = "CAPABILITY_DISABLED_QUEUED_INTERRUPT"
    CAPABILITY_DISABLED_MODEL_SELECTION = "CAPABILITY_DISABLED_MODEL_SELECTION"

    # Prompt Navigator (dot rail)
    PROMPT_NAVIGATOR_DOT = "PROMPT_NAVIGATOR_DOT"
    PROMPT_NAVIGATOR_UP_BUTTON = "PROMPT_NAVIGATOR_UP_BUTTON"
    PROMPT_NAVIGATOR_DOWN_BUTTON = "PROMPT_NAVIGATOR_DOWN_BUTTON"
    PROMPT_NAVIGATOR_COLLAPSED_INDICATOR = "PROMPT_NAVIGATOR_COLLAPSED_INDICATOR"

    FILE_PREVIEW_LIST = "FILE_PREVIEW_LIST"
    FILE_PREVIEW = "FILE_PREVIEW"
    FILE_PREVIEW_REMOVE = "FILE_PREVIEW_REMOVE"
    FILE_PREVIEW_CONTAINER = "FILE_PREVIEW_CONTAINER"
    FILE_PREVIEW_COPY_IMAGE = "FILE_PREVIEW_COPY_IMAGE"
    FILE_UPLOAD = "FILE_UPLOAD"

    # Image Lightbox
    LIGHTBOX_NAV_PREVIOUS = "LIGHTBOX_NAV_PREVIOUS"
    LIGHTBOX_NAV_NEXT = "LIGHTBOX_NAV_NEXT"
    LIGHTBOX_COUNTER = "LIGHTBOX_COUNTER"

    # File Browser Panel
    FILE_BROWSER_PANEL = "FILE_BROWSER_PANEL"
    FILE_BROWSER_COLLAPSE_FOLDERS_BTN = "FILE_BROWSER_COLLAPSE_FOLDERS_BTN"
    FILE_BROWSER_REFRESH_BTN = "FILE_BROWSER_REFRESH_BTN"
    FILE_BROWSER_SEARCH_FILES_BTN = "FILE_BROWSER_SEARCH_FILES_BTN"
    FILE_BROWSER_EMPTY = "FILE_BROWSER_EMPTY"
    FILE_BROWSER_SKELETON = "FILE_BROWSER_SKELETON"
    FILE_BROWSER_FILE_TREE = "FILE_BROWSER_FILE_TREE"
    FILE_BROWSER_TREE_ROW = "FILE_BROWSER_TREE_ROW"
    FILE_BROWSER_TREE_ROW_STATUS = "FILE_BROWSER_TREE_ROW_STATUS"
    FILE_BROWSER_SEARCH_INPUT = "FILE_BROWSER_SEARCH_INPUT"
    FILE_BROWSER_SEARCH_CLOSE = "FILE_BROWSER_SEARCH_CLOSE"
    FILE_BROWSER_CHANGES_TREE = "FILE_BROWSER_CHANGES_TREE"
    # Diff Panel
    DIFF_PANEL = "DIFF_PANEL"
    DIFF_TAB = "DIFF_TAB"
    # Hidden marker rendered inside file-view tab labels so tests can
    # distinguish a file-view tab from a single-diff / combined / commit-diff
    # tab without a CSS-attribute locator on the tab id prefix.
    FILE_VIEW_TAB_MARKER = "FILE_VIEW_TAB_MARKER"
    DIFF_FILE_HEADER = "DIFF_FILE_HEADER"
    DIFF_FILE_HEADER_MENU_TRIGGER = "DIFF_FILE_HEADER_MENU_TRIGGER"
    COMBINED_DIFF_FILE_SECTION = "COMBINED_DIFF_FILE_SECTION"
    DIFF_VIEW_UNIFIED = "DIFF_VIEW_UNIFIED"
    DIFF_VIEW_SPLIT = "DIFF_VIEW_SPLIT"
    DIFF_SPLIT_VIEW_TOGGLE = "DIFF_SPLIT_VIEW_TOGGLE"
    DIFF_SPLIT_COLUMN_HANDLE = "DIFF_SPLIT_COLUMN_HANDLE"
    DIFF_RENAME_BANNER = "DIFF_RENAME_BANNER"
    DIFF_LINE_WRAP_TOGGLE = "DIFF_LINE_WRAP_TOGGLE"
    DIFF_RENDER_TOGGLE = "DIFF_RENDER_TOGGLE"
    DIFF_FIND_IN_FILE_BTN = "DIFF_FIND_IN_FILE_BTN"
    DIFF_IN_FILE_SEARCH_BAR = "DIFF_IN_FILE_SEARCH_BAR"
    DIFF_IN_FILE_SEARCH_INPUT = "DIFF_IN_FILE_SEARCH_INPUT"
    READ_ONLY_PREVIEW = "READ_ONLY_PREVIEW"
    READ_ONLY_PREVIEW_MARKDOWN = "READ_ONLY_PREVIEW_MARKDOWN"

    # Changes Panel
    CHANGES_PANEL = "CHANGES_PANEL"
    CHANGES_REVIEW_ALL_BTN = "CHANGES_REVIEW_ALL_BTN"
    CHANGES_COMMIT_BUTTON = "CHANGES_COMMIT_BUTTON"
    HISTORY_PANEL = "HISTORY_PANEL"
    HISTORY_COMMIT_ENTRY = "HISTORY_COMMIT_ENTRY"
    HISTORY_COMMIT_MESSAGE = "HISTORY_COMMIT_MESSAGE"
    HISTORY_COMMIT_META = "HISTORY_COMMIT_META"
    HISTORY_COMMIT_POPOVER = "HISTORY_COMMIT_POPOVER"
    HISTORY_TERMINUS = "HISTORY_TERMINUS"
    HISTORY_MERGE_SPUR = "HISTORY_MERGE_SPUR"
    DIFF_SCOPE_PICKER = "DIFF_SCOPE_PICKER"
    DIFF_SCOPE_UNCOMMITTED = "DIFF_SCOPE_UNCOMMITTED"
    DIFF_SCOPE_ALL = "DIFF_SCOPE_ALL"
    DIFF_EXPAND_TOGGLE = "DIFF_EXPAND_TOGGLE"
    DIFF_CLOSE_PANEL_BUTTON = "DIFF_CLOSE_PANEL_BUTTON"
    DISCARD_BUTTON = "DISCARD_BUTTON"
    DISCARD_DIALOG = "DISCARD_DIALOG"
    DISCARD_DIALOG_CONFIRM = "DISCARD_DIALOG_CONFIRM"
    DISCARD_DIALOG_CANCEL = "DISCARD_DIALOG_CANCEL"

    # Terminal Panel
    TERMINAL_HEADING = "TERMINAL_HEADING"
    TERMINAL_STARTING_TEXT = "TERMINAL_STARTING_TEXT"
    ADD_TERMINAL_BUTTON = "ADD_TERMINAL_BUTTON"
    TERMINAL_TAB = "TERMINAL_TAB"

    # Panel Icons (sidebar)
    PANEL_ICON_FILES = "PANEL_ICON_FILES"
    FILE_BROWSER_TAB_ALL = "FILE_BROWSER_TAB_ALL"
    FILE_BROWSER_TAB_CHANGES = "FILE_BROWSER_TAB_CHANGES"
    FILE_BROWSER_TAB_HISTORY = "FILE_BROWSER_TAB_HISTORY"
    PANEL_ICON_ACTIONS = "PANEL_ICON_ACTIONS"
    PANEL_ICON_TERMINAL = "PANEL_ICON_TERMINAL"
    PANEL_ICON_BROWSER = "PANEL_ICON_BROWSER"
    PANEL_ICON_SKILLS = "PANEL_ICON_SKILLS"

    # Browser Panel
    BROWSER_PANEL = "BROWSER_PANEL"
    BROWSER_WEB_MODE_PLACEHOLDER = "BROWSER_WEB_MODE_PLACEHOLDER"
    BROWSER_URL_INPUT = "BROWSER_URL_INPUT"
    BROWSER_URL_ERROR = "BROWSER_URL_ERROR"
    BROWSER_BACK_BTN = "BROWSER_BACK_BTN"
    BROWSER_FORWARD_BTN = "BROWSER_FORWARD_BTN"
    BROWSER_REFRESH_BTN = "BROWSER_REFRESH_BTN"
    BROWSER_SCREENSHOT_BTN = "BROWSER_SCREENSHOT_BTN"
    BROWSER_WEBVIEW = "BROWSER_WEBVIEW"

    # Panel Containers (docking layout)
    PANEL_TOP_RIGHT = "PANEL_TOP_RIGHT"
    PANEL_BOTTOM_RIGHT = "PANEL_BOTTOM_RIGHT"
    PANEL_RIGHT_AREA = "PANEL_RIGHT_AREA"
    PANEL_RIGHT_RESIZE_HANDLE = "PANEL_RIGHT_RESIZE_HANDLE"

    # Bottom Bar
    BOTTOM_BAR = "BOTTOM_BAR"

    # Panel Side Toggle Buttons (bottom bar)
    SIDE_TOGGLE_LEFT = "SIDE_TOGGLE_LEFT"
    SIDE_TOGGLE_BOTTOM = "SIDE_TOGGLE_BOTTOM"
    SIDE_TOGGLE_RIGHT = "SIDE_TOGGLE_RIGHT"

    # Zen mode
    EXIT_ZEN_MODE_BUTTON = "EXIT_ZEN_MODE_BUTTON"

    # Focus mode
    FOCUS_MODE_BUTTON = "FOCUS_MODE_BUTTON"

    # Panel Context Menu
    PANEL_CONTEXT_MENU_MOVE_TO = "PANEL_CONTEXT_MENU_MOVE_TO"
    PANEL_CONTEXT_MENU_ZONE_OPTION = "PANEL_CONTEXT_MENU_ZONE_OPTION"

    # Agent tasks popover (StatusPill)
    AGENT_TASKS_EMPTY_STATE = "AGENT_TASKS_EMPTY_STATE"

    # Agent tasks popover (DAG-aware)
    AGENT_TASKS_ROW = "AGENT_TASKS_ROW"
    AGENT_TASKS_ROW_DETAIL = "AGENT_TASKS_ROW_DETAIL"
    AGENT_TASKS_WAITING_BADGE = "AGENT_TASKS_WAITING_BADGE"
    AGENT_TASKS_GRAPH_TOGGLE = "AGENT_TASKS_GRAPH_TOGGLE"
    AGENT_TASKS_GRAPH = "AGENT_TASKS_GRAPH"
    AGENT_TASKS_GRAPH_NODE = "AGENT_TASKS_GRAPH_NODE"

    # Skills Panel
    SKILLS_PANEL = "SKILLS_PANEL"
    SKILL_CHIP = "SKILL_CHIP"
    SKILLS_PANEL_SEARCH_TOGGLE = "SKILLS_PANEL_SEARCH_TOGGLE"
    SKILLS_PANEL_SEARCH_INPUT = "SKILLS_PANEL_SEARCH_INPUT"

    ARTIFACT_FILE = "ARTIFACT_FILE"
    ARTIFACT_FILE_HEADER = "ARTIFACT_FILE_HEADER"
    ARTIFACT_FILE_DROPDOWN = "ARTIFACT_FILE_DROPDOWN"
    ARTIFACT_FILE_BODY = "ARTIFACT_FILE_BODY"
    ARTIFACT_FILE_NAME = "ARTIFACT_FILE_NAME"
    OPEN_IN_VIEWER_BUTTON = "OPEN_IN_VIEWER_BUTTON"

    ARTIFACT_PLAN_CHECKMARK = "ARTIFACT_PLAN_CHECKMARK"

    # File Mention Suggestions
    MENTION_LIST = "MENTION_LIST"
    MENTION_SPAN = "MENTION_SPAN"
    FILE_MENTION_SUGGESTION_ITEM = "FILE_MENTION_SUGGESTION_ITEM"

    # Entity Mention Suggestions
    ENTITY_MENTION_LIST = "ENTITY_MENTION_LIST"
    ENTITY_MENTION_ITEM = "ENTITY_MENTION_ITEM"
    ENTITY_MENTION_CHIP = "ENTITY_MENTION_CHIP"

    # `+` prefilter mention picker
    MENTION_PICKER_TOOLBAR_BUTTON = "MENTION_PICKER_TOOLBAR_BUTTON"
    MENTION_PICKER_CATEGORY_ITEM = "MENTION_PICKER_CATEGORY_ITEM"

    # Common UI Elements
    TOAST = "TOAST"
    TOAST_CLOSE_BUTTON = "TOAST_CLOSE_BUTTON"
    TOAST_ACTION_BUTTON = "TOAST_ACTION_BUTTON"

    # Onboarding page
    ONBOARDING_PATH_CHECK_STEP = "ONBOARDING_PATH_CHECK_STEP"
    ONBOARDING_PATH_CHECK_CONTINUE = "ONBOARDING_PATH_CHECK_CONTINUE"
    ONBOARDING_TOOL_STATUS_CLAUDE = "ONBOARDING_TOOL_STATUS_CLAUDE"
    ONBOARDING_TOOL_STATUS_GIT = "ONBOARDING_TOOL_STATUS_GIT"
    ONBOARDING_TOOL_MISSING_CLAUDE_MESSAGE = "ONBOARDING_TOOL_MISSING_CLAUDE_MESSAGE"
    ONBOARDING_ADD_REPO_STEP = "ONBOARDING_ADD_REPO_STEP"
    ONBOARDING_STEP_INDICATOR_DOT = "ONBOARDING_STEP_INDICATOR_DOT"

    # Project selector page
    PROJECT_GIT_INIT_DIALOG = "PROJECT_GIT_INIT_DIALOG"
    PROJECT_GIT_INIT_CONFIRM = "PROJECT_GIT_INIT_CONFIRM"
    PROJECT_GIT_INIT_CANCEL = "PROJECT_GIT_INIT_CANCEL"
    PROJECT_INITIAL_COMMIT_CONFIRM = "PROJECT_INITIAL_COMMIT_CONFIRM"

    # Settings page
    SETTINGS_PAGE = "SETTINGS_PAGE"
    SETTINGS_CONTENT = "SETTINGS_CONTENT"
    SETTINGS_NAV_GENERAL = "SETTINGS_NAV_GENERAL"
    SETTINGS_NAV_KEYBINDINGS = "SETTINGS_NAV_KEYBINDINGS"
    SETTINGS_NAV_PANELS = "SETTINGS_NAV_PANELS"
    SETTINGS_PANELS_ROW = "SETTINGS_PANELS_ROW"
    SETTINGS_PANELS_ZONE_SELECT = "SETTINGS_PANELS_ZONE_SELECT"
    SETTINGS_PANELS_ENABLED_SWITCH = "SETTINGS_PANELS_ENABLED_SWITCH"
    SETTINGS_PANELS_DIAGRAM = "SETTINGS_PANELS_DIAGRAM"
    SETTINGS_PANELS_DIAGRAM_ZONE = "SETTINGS_PANELS_DIAGRAM_ZONE"
    SETTINGS_PANELS_DIAGRAM_ICON = "SETTINGS_PANELS_DIAGRAM_ICON"
    SETTINGS_PANELS_DIAGRAM_CLEAR_FILTER = "SETTINGS_PANELS_DIAGRAM_CLEAR_FILTER"
    PANEL_CONTEXT_MENU_CONFIGURE = "PANEL_CONTEXT_MENU_CONFIGURE"
    SETTINGS_PANELS_RESET_DEFAULTS = "SETTINGS_PANELS_RESET_DEFAULTS"
    SETTINGS_NAV_PRIVACY = "SETTINGS_NAV_PRIVACY"
    SETTINGS_PRIVACY_TELEMETRY_ROW = "SETTINGS_PRIVACY_TELEMETRY_ROW"
    SETTINGS_PRIVACY_TELEMETRY_SWITCH = "SETTINGS_PRIVACY_TELEMETRY_SWITCH"
    SETTINGS_PRIVACY_TELEMETRY_DIALOG = "SETTINGS_PRIVACY_TELEMETRY_DIALOG"
    SETTINGS_PRIVACY_TELEMETRY_DIALOG_CONFIRM = "SETTINGS_PRIVACY_TELEMETRY_DIALOG_CONFIRM"
    SETTINGS_PRIVACY_TELEMETRY_DIALOG_CANCEL = "SETTINGS_PRIVACY_TELEMETRY_DIALOG_CANCEL"
    SETTINGS_PANELS_PLUGIN_BADGE = "SETTINGS_PANELS_PLUGIN_BADGE"
    SETTINGS_NAV_PLUGINS = "SETTINGS_NAV_PLUGINS"
    SETTINGS_PLUGINS_LIST = "SETTINGS_PLUGINS_LIST"
    SETTINGS_PLUGINS_EMPTY = "SETTINGS_PLUGINS_EMPTY"
    SETTINGS_PLUGINS_SOURCE_INPUT = "SETTINGS_PLUGINS_SOURCE_INPUT"
    SETTINGS_PLUGINS_ADD_BUTTON = "SETTINGS_PLUGINS_ADD_BUTTON"
    SETTINGS_PLUGINS_SOURCE_ROW = "SETTINGS_PLUGINS_SOURCE_ROW"
    SETTINGS_PLUGINS_SOURCE_REMOVE = "SETTINGS_PLUGINS_SOURCE_REMOVE"
    SETTINGS_PLUGINS_SOURCE_TOGGLE = "SETTINGS_PLUGINS_SOURCE_TOGGLE"
    SETTINGS_PLUGINS_SOURCE_RELOAD = "SETTINGS_PLUGINS_SOURCE_RELOAD"
    SETTINGS_PLUGINS_SOURCE_SETTINGS = "SETTINGS_PLUGINS_SOURCE_SETTINGS"
    SETTINGS_PLUGINS_REFRESH_BUTTON = "SETTINGS_PLUGINS_REFRESH_BUTTON"
    SETTINGS_PLUGINS_DIRECTORY = "SETTINGS_PLUGINS_DIRECTORY"
    SETTINGS_NAV_REPOSITORIES = "SETTINGS_NAV_REPOSITORIES"
    SETTINGS_NAV_ACTIONS = "SETTINGS_NAV_ACTIONS"
    SETTINGS_NAV_GIT = "SETTINGS_NAV_GIT"
    SETTINGS_NAV_CI = "SETTINGS_NAV_CI"
    SETTINGS_NAV_FILE_BROWSER = "SETTINGS_NAV_FILE_BROWSER"
    SETTINGS_NAV_EXPERIMENTAL = "SETTINGS_NAV_EXPERIMENTAL"
    SETTINGS_NAV_PROJECT_ENV_VARS = "SETTINGS_NAV_PROJECT_ENV_VARS"
    SETTINGS_ENV_VAR_OVERRIDE_TOGGLE = "SETTINGS_ENV_VAR_OVERRIDE_TOGGLE"
    SETTINGS_ENV_VAR_NAMES_LIST = "SETTINGS_ENV_VAR_NAMES_LIST"
    SETTINGS_DEFAULT_MODEL_SELECT = "SETTINGS_DEFAULT_MODEL_SELECT"
    SETTINGS_DEFAULT_MODEL_OPTION = "SETTINGS_DEFAULT_MODEL_OPTION"
    SETTINGS_THEME_SELECT = "SETTINGS_THEME_SELECT"
    SETTINGS_ALWAYS_INTERRUPT_SELECT = "SETTINGS_ALWAYS_INTERRUPT_SELECT"
    SETTINGS_ALWAYS_INTERRUPT_OPTION = "SETTINGS_ALWAYS_INTERRUPT_OPTION"
    SETTINGS_ALWAYS_INTERRUPT_DISABLED_OPTION = "SETTINGS_ALWAYS_INTERRUPT_DISABLED_OPTION"

    # Agent settings
    SETTINGS_NAV_AGENT = "SETTINGS_NAV_AGENT"
    SETTINGS_DEFAULT_FAST_MODE_TOGGLE = "SETTINGS_DEFAULT_FAST_MODE_TOGGLE"
    SETTINGS_DEFAULT_EFFORT_LEVEL_SELECT = "SETTINGS_DEFAULT_EFFORT_LEVEL_SELECT"
    SETTINGS_DEFAULT_EFFORT_LEVEL_OPTION = "SETTINGS_DEFAULT_EFFORT_LEVEL_OPTION"

    # Dependencies settings
    SETTINGS_NAV_DEPENDENCIES = "SETTINGS_NAV_DEPENDENCIES"
    CLAUDE_CLI_MODE_SELECTOR = "claude-cli-mode-selector"
    CLAUDE_CLI_INSTALL_BUTTON = "claude-cli-install-button"
    CLAUDE_CLI_VERSION = "claude-cli-version"
    CLAUDE_CLI_STATUS = "claude-cli-status"
    CLAUDE_CLI_PROGRESS = "claude-cli-progress"
    CLAUDE_CLI_CUSTOM_PATH_INPUT = "claude-cli-custom-path-input"
    CLAUDE_CLI_VERSION_POPOVER = "claude-cli-version-popover"
    CLAUDE_CLI_MODE_POPOVER = "claude-cli-mode-popover"
    CLAUDE_CLI_MODE_OPTION_MANAGED = "claude-cli-mode-option-managed"
    CLAUDE_CLI_MODE_OPTION_CUSTOM = "claude-cli-mode-option-custom"
    CLAUDE_CLI_UP_TO_DATE = "claude-cli-up-to-date"
    CLAUDE_CLI_MODE_SETTLING = "claude-cli-mode-settling"

    # Settings > Dependencies > Git
    SETTINGS_GIT_DEP_STATUS = "settings-git-dep-status"

    # Pi settings
    SETTINGS_NAV_PI = "SETTINGS_NAV_PI"
    PI_BINARY_PATH_INPUT = "pi-binary-path-input"
    PI_BINARY_PATH_APPLY = "pi-binary-path-apply"
    PI_STATUS = "pi-status"
    PI_VERSION = "pi-version"
    PI_PINNED_VERSION = "pi-pinned-version"
    PI_ENV_VAR_NAMES_LIST = "pi-env-var-names-list"
    PI_ENV_VAR_NAME_INPUT = "pi-env-var-name-input"
    PI_ENV_VAR_NAME_ADD = "pi-env-var-name-add"
    PI_ENV_VAR_NAME_REMOVE = "pi-env-var-name-remove"
    # Managed-install controls, mirroring the CLAUDE_CLI_* set.
    PI_MODE_SELECTOR = "pi-mode-selector"
    PI_MODE_OPTION_MANAGED = "pi-mode-option-managed"
    PI_MODE_OPTION_CUSTOM = "pi-mode-option-custom"
    PI_INSTALL_BUTTON = "pi-install-button"
    PI_INSTALL_PROGRESS = "pi-install-progress"
    PI_UP_TO_DATE = "pi-up-to-date"

    # Repository settings
    SETTINGS_REPO_ROW = "SETTINGS_REPO_ROW"
    SETTINGS_REMOVE_REPO_BUTTON = "SETTINGS_REMOVE_REPO_BUTTON"
    SETTINGS_REMOVE_REPO_CONFIRM = "SETTINGS_REMOVE_REPO_CONFIRM"
    SETTINGS_ADD_REPO_BUTTON = "SETTINGS_ADD_REPO_BUTTON"
    SETTINGS_WORKSPACE_SETUP_COMMAND_INPUT = "SETTINGS_WORKSPACE_SETUP_COMMAND_INPUT"
    SETTINGS_REPO_ROW_CONFIG_TOGGLE = "SETTINGS_REPO_ROW_CONFIG_TOGGLE"
    SETTINGS_NAMING_PATTERN_INPUT = "SETTINGS_NAMING_PATTERN_INPUT"
    SETTINGS_GLOBAL_NAMING_PATTERN_INPUT = "SETTINGS_GLOBAL_NAMING_PATTERN_INPUT"
    SETTINGS_DEFAULT_TARGET_BRANCH_INPUT = "SETTINGS_DEFAULT_TARGET_BRANCH_INPUT"
    SETTINGS_POLL_INTERVAL_INPUT = "SETTINGS_POLL_INTERVAL_INPUT"
    SETTINGS_POLL_CLOSED_MULTIPLIER_INPUT = "SETTINGS_POLL_CLOSED_MULTIPLIER_INPUT"
    SETTINGS_POLLING_ENABLED_TOGGLE = "SETTINGS_POLLING_ENABLED_TOGGLE"
    SETTINGS_BRANCH_DELETION_POLICY_SELECT = "SETTINGS_BRANCH_DELETION_POLICY_SELECT"
    SETTINGS_ENABLE_CLONE_WORKSPACES_TOGGLE = "SETTINGS_ENABLE_CLONE_WORKSPACES_TOGGLE"

    # Setup Status
    SETUP_RERUN_BUTTON = "setup-rerun-button"
    SETUP_CONFIG_PROMPT = "setup-config-prompt"
    SETUP_CONFIG_SETTINGS_LINK = "setup-config-settings-link"
    SETUP_STATUS_CARD = "setup-status-card"
    SETUP_STATUS_OUTPUT = "setup-status-output"
    SETUP_STATUS_TRUNCATION = "setup-status-truncation"
    SETUP_CANCEL_BUTTON = "setup-cancel-button"
    SETUP_RUN_BUTTON = "setup-run-button"
    SETUP_EDIT_BUTTON = "setup-edit-button"

    # Add Repo Dialog
    ADD_REPO_DIALOG = "ADD_REPO_DIALOG"
    ADD_REPO_PATH_INPUT = "ADD_REPO_PATH_INPUT"
    ADD_REPO_SUBMIT_BUTTON = "ADD_REPO_SUBMIT_BUTTON"
    ADD_REPO_BROWSE_LINK = "ADD_REPO_BROWSE_LINK"
    PATH_AUTOCOMPLETE_ITEM = "PATH_AUTOCOMPLETE_ITEM"
    PATH_AUTOCOMPLETE_SUBMIT_HINT = "PATH_AUTOCOMPLETE_SUBMIT_HINT"

    # Hotkey fields
    SETTINGS_HOTKEY_CLEAR_BUTTON = "SETTINGS_HOTKEY_CLEAR_BUTTON"
    SETTINGS_HOTKEY_SET_BUTTON = "SETTINGS_HOTKEY_SET_BUTTON"

    # Keybindings section
    SETTINGS_KEYBINDINGS_SEARCH = "SETTINGS_KEYBINDINGS_SEARCH"
    SETTINGS_KEYBINDINGS_RESET_ALL = "SETTINGS_KEYBINDINGS_RESET_ALL"
    SETTINGS_KEYBINDINGS_CONFLICT_WARNING = "SETTINGS_KEYBINDINGS_CONFLICT_WARNING"
    SETTINGS_KEYBINDINGS_REASSIGN = "SETTINGS_KEYBINDINGS_REASSIGN"
    SETTINGS_KEYBINDINGS_CANCEL_CONFLICT = "SETTINGS_KEYBINDINGS_CANCEL_CONFLICT"

    # Help dialog shortcut rows
    HELP_SHORTCUT_ROW = "HELP_SHORTCUT_ROW"

    # Account fields
    SETTINGS_EMAIL_FIELD = "SETTINGS_EMAIL_FIELD"

    # Actions Panel
    ACTIONS_PANEL = "ACTIONS_PANEL"
    ACTIONS_PANEL_ADD_BUTTON = "ACTIONS_PANEL_ADD_BUTTON"
    ACTION_CHIP = "ACTION_CHIP"

    # Action Dialog (shared between panel and settings)
    ACTION_DIALOG = "ACTION_DIALOG"
    ACTION_DIALOG_NAME_INPUT = "ACTION_DIALOG_NAME_INPUT"
    ACTION_DIALOG_PROMPT_INPUT = "ACTION_DIALOG_PROMPT_INPUT"
    ACTION_DIALOG_SAVE_BUTTON = "ACTION_DIALOG_SAVE_BUTTON"
    ACTION_DIALOG_AUTO_SUBMIT_SWITCH = "ACTION_DIALOG_AUTO_SUBMIT_SWITCH"
    ACTION_DIALOG_GROUP_SELECT = "ACTION_DIALOG_GROUP_SELECT"
    ACTION_DIALOG_NEW_GROUP_NAME_INPUT = "ACTION_DIALOG_NEW_GROUP_NAME_INPUT"

    # Delete Action Dialog
    DELETE_ACTION_DIALOG = "DELETE_ACTION_DIALOG"
    DELETE_ACTION_CONFIRM_BUTTON = "DELETE_ACTION_CONFIRM_BUTTON"

    # Delete Group Dialog
    DELETE_GROUP_CONFIRM_BUTTON = "DELETE_GROUP_CONFIRM_BUTTON"

    # Settings page - Actions section
    SETTINGS_ACTIONS_SECTION = "SETTINGS_ACTIONS_SECTION"
    SETTINGS_ACTIONS_ADD_BUTTON = "SETTINGS_ACTIONS_ADD_BUTTON"
    SETTINGS_ACTIONS_ADD_GROUP_BUTTON = "SETTINGS_ACTIONS_ADD_GROUP_BUTTON"
    SETTINGS_ACTIONS_EXPORT_BUTTON = "SETTINGS_ACTIONS_EXPORT_BUTTON"
    SETTINGS_ACTIONS_IMPORT_BUTTON = "SETTINGS_ACTIONS_IMPORT_BUTTON"
    SETTINGS_ACTION_ROW = "SETTINGS_ACTION_ROW"
    SETTINGS_ACTION_EDIT_BUTTON = "SETTINGS_ACTION_EDIT_BUTTON"
    SETTINGS_ACTION_DELETE_BUTTON = "SETTINGS_ACTION_DELETE_BUTTON"
    SETTINGS_GROUP_DELETE_BUTTON = "SETTINGS_GROUP_DELETE_BUTTON"
    SETTINGS_ACTIONS_GROUP_NAME_INPUT = "SETTINGS_ACTIONS_GROUP_NAME_INPUT"
    SETTINGS_ACTIONS_CREATE_GROUP_BUTTON = "SETTINGS_ACTIONS_CREATE_GROUP_BUTTON"
    SETTINGS_ACTIONS_GROUP_HEADING = "SETTINGS_ACTIONS_GROUP_HEADING"
    ACTIONS_PANEL_GROUP_HEADER = "ACTIONS_PANEL_GROUP_HEADER"
    GROUP_CONTEXT_MENU_DELETE = "GROUP_CONTEXT_MENU_DELETE"

    # Warning Status Banner
    WARNING_STATUS_BANNER = "WARNING_STATUS_BANNER"
    WARNING_STATUS_BANNER_LINK = "WARNING_STATUS_BANNER_LINK"

    # Project Path Dialog
    PROJECT_PATH_DIALOG = "PROJECT_PATH_DIALOG"
    PROJECT_PATH_DIALOG_CLOSE_BUTTON = "PROJECT_PATH_DIALOG_CLOSE_BUTTON"

    # Workspace tabs
    WORKSPACE_TAB = "WORKSPACE_TAB"
    HOME_TAB = "HOME_TAB"
    SETTINGS_TAB = "SETTINGS_TAB"
    ADD_WORKSPACE_TAB = "ADD_WORKSPACE_TAB"
    TAB_CLOSE_BUTTON = "TAB_CLOSE_BUTTON"
    ADD_WORKSPACE_BUTTON = "ADD_WORKSPACE_BUTTON"
    WORKSPACE_NAME_INPUT = "WORKSPACE_NAME_INPUT"
    WORKSPACE_ROW = "WORKSPACE_ROW"
    WORKSPACE_ROW_BRANCH = "WORKSPACE_ROW_BRANCH"
    WORKSPACE_SEARCH_INPUT = "WORKSPACE_SEARCH_INPUT"
    ADD_WORKSPACE_EMPTY_STATE = "ADD_WORKSPACE_EMPTY_STATE"

    # Closed workspaces
    CLOSED_WORKSPACES_PILL = "CLOSED_WORKSPACES_PILL"
    CLOSED_WORKSPACES_DROPDOWN = "CLOSED_WORKSPACES_DROPDOWN"
    CLOSED_WORKSPACE_ROW = "CLOSED_WORKSPACE_ROW"
    CLOSED_WORKSPACE_DELETE_BUTTON = "CLOSED_WORKSPACE_DELETE_BUTTON"
    CLOSED_WORKSPACES_OPEN_ALL_BUTTON = "CLOSED_WORKSPACES_OPEN_ALL_BUTTON"

    # Agent tabs (within a workspace)
    AGENT_TAB = "AGENT_TAB"
    ADD_AGENT_BUTTON = "ADD_AGENT_BUTTON"
    ADD_AGENT_CHEVRON_BUTTON = "ADD_AGENT_CHEVRON_BUTTON"
    AGENT_TYPE_MENU = "AGENT_TYPE_MENU"
    AGENT_TYPE_MENU_ITEM_CLAUDE = "AGENT_TYPE_MENU_ITEM_CLAUDE"
    AGENT_TYPE_MENU_ITEM_PI = "AGENT_TYPE_MENU_ITEM_PI"
    AGENT_TYPE_MENU_ITEM_TERMINAL = "AGENT_TYPE_MENU_ITEM_TERMINAL"
    # Registered terminal agents share one testid; tests disambiguate via the
    # data-registration-id attribute set alongside it.
    AGENT_TYPE_MENU_ITEM_REGISTERED = "AGENT_TYPE_MENU_ITEM_REGISTERED"
    AGENT_TERMINAL_PANEL = "AGENT_TERMINAL_PANEL"
    # Add Workspace form's first-agent type picker
    ADD_WORKSPACE_AGENT_TYPE_SELECT = "ADD_WORKSPACE_AGENT_TYPE_SELECT"
    AGENT_TYPE_OPTION_CLAUDE = "AGENT_TYPE_OPTION_CLAUDE"
    AGENT_TYPE_OPTION_PI = "AGENT_TYPE_OPTION_PI"
    AGENT_TYPE_OPTION_TERMINAL = "AGENT_TYPE_OPTION_TERMINAL"
    AGENT_TYPE_OPTION_REGISTERED = "AGENT_TYPE_OPTION_REGISTERED"

    # Tab shared components
    INLINE_RENAME_INPUT = "INLINE_RENAME_INPUT"
    TAB_CONTEXT_MENU_RENAME = "TAB_CONTEXT_MENU_RENAME"
    TAB_CONTEXT_MENU_DELETE = "TAB_CONTEXT_MENU_DELETE"
    TAB_CONTEXT_MENU_CLOSE = "TAB_CONTEXT_MENU_CLOSE"
    TAB_CONTEXT_MENU_CLOSE_OTHERS = "TAB_CONTEXT_MENU_CLOSE_OTHERS"
    TAB_CONTEXT_MENU_CLOSE_ALL = "TAB_CONTEXT_MENU_CLOSE_ALL"
    TAB_CONTEXT_MENU_DIAGNOSTICS = "TAB_CONTEXT_MENU_DIAGNOSTICS"
    TAB_CONTEXT_MENU_COPY_SESSION_ID = "TAB_CONTEXT_MENU_COPY_SESSION_ID"
    TAB_CONTEXT_MENU_COPY_TRANSCRIPT_PATH = "TAB_CONTEXT_MENU_COPY_TRANSCRIPT_PATH"
    TAB_CONTEXT_MENU_MARK_UNREAD = "TAB_CONTEXT_MENU_MARK_UNREAD"
    TAB_CONTEXT_MENU_COPY_SCULPTOR_TRANSCRIPT_PATH = "TAB_CONTEXT_MENU_COPY_SCULPTOR_TRANSCRIPT_PATH"
    TAB_CONTEXT_MENU_COPY_AGENT_ID = "TAB_CONTEXT_MENU_COPY_AGENT_ID"
    TAB_CONTEXT_MENU_COPY_AGENT_NAME = "TAB_CONTEXT_MENU_COPY_AGENT_NAME"
    TAB_CONTEXT_MENU_COPY_WORKSPACE_ID = "TAB_CONTEXT_MENU_COPY_WORKSPACE_ID"
    TAB_CONTEXT_MENU_COPY_WORKSPACE_NAME = "TAB_CONTEXT_MENU_COPY_WORKSPACE_NAME"
    TAB_CONTEXT_MENU_COPY_BRANCH = "TAB_CONTEXT_MENU_COPY_BRANCH"
    WORKSPACE_ROW_CONTEXT_MENU_DELETE = "WORKSPACE_ROW_CONTEXT_MENU_DELETE"
    DELETE_CONFIRMATION_DIALOG = "DELETE_CONFIRMATION_DIALOG"
    DELETE_CONFIRMATION_CONFIRM = "DELETE_CONFIRMATION_CONFIRM"
    DELETE_CONFIRMATION_CANCEL = "DELETE_CONFIRMATION_CANCEL"

    # PR management
    TARGET_BRANCH_SELECTOR = "TARGET_BRANCH_SELECTOR"
    PR_BUTTON_ASSIGN = "PR_BUTTON_ASSIGN"
    PR_BUTTON_CREATE = "PR_BUTTON_CREATE"
    PR_BUTTON_OPEN = "PR_BUTTON_OPEN"
    PR_BUTTON_CHEVRON = "PR_BUTTON_CHEVRON"
    PR_BUTTON_MERGED = "PR_BUTTON_MERGED"
    PR_BUTTON_ERROR = "PR_BUTTON_ERROR"
    PR_BUTTON_ERROR_POPOVER = "PR_BUTTON_ERROR_POPOVER"
    PR_BUTTON_ERROR_DETAILS = "PR_BUTTON_ERROR_DETAILS"
    PR_DROPDOWN = "PR_DROPDOWN"
    PR_PROMPT_DIALOG = "PR_PROMPT_DIALOG"

    # CI Babysitter (experimental)
    PR_BABYSITTER_PAUSE_TOGGLE = "PR_BABYSITTER_PAUSE_TOGGLE"
    PR_BABYSITTER_STATUS = "PR_BABYSITTER_STATUS"
    SETTINGS_CI_BABYSITTER_ENABLED_TOGGLE = "SETTINGS_CI_BABYSITTER_ENABLED_TOGGLE"
    SETTINGS_CI_BABYSITTER_RETRY_CAP_INPUT = "SETTINGS_CI_BABYSITTER_RETRY_CAP_INPUT"
    SETTINGS_CI_BABYSITTER_PIPELINE_PROMPT_TEXTAREA = "SETTINGS_CI_BABYSITTER_PIPELINE_PROMPT_TEXTAREA"
    SETTINGS_CI_BABYSITTER_MERGE_CONFLICT_PROMPT_TEXTAREA = "SETTINGS_CI_BABYSITTER_MERGE_CONFLICT_PROMPT_TEXTAREA"
    SETTINGS_CI_BABYSITTER_AGENT_SELECT = "SETTINGS_CI_BABYSITTER_AGENT_SELECT"

    # In-place workspaces (experimental)
    SETTINGS_ENABLE_IN_PLACE_WORKSPACES_TOGGLE = "SETTINGS_ENABLE_IN_PLACE_WORKSPACES_TOGGLE"

    # Review All (experimental)
    SETTINGS_ENABLE_REVIEW_ALL_TOGGLE = "SETTINGS_ENABLE_REVIEW_ALL_TOGGLE"

    # Entity Mentions (experimental)
    SETTINGS_ENABLE_ENTITY_MENTIONS_TOGGLE = "SETTINGS_ENABLE_ENTITY_MENTIONS_TOGGLE"

    # Rich markdown rendering (experimental)
    SETTINGS_ENABLE_RICH_MARKDOWN_RENDERING_TOGGLE = "SETTINGS_ENABLE_RICH_MARKDOWN_RENDERING_TOGGLE"

    # Pi agent (experimental)
    SETTINGS_ENABLE_PI_AGENT_TOGGLE = "SETTINGS_ENABLE_PI_AGENT_TOGGLE"
    SETTINGS_ENABLE_FRONTEND_PLUGINS_TOGGLE = "SETTINGS_ENABLE_FRONTEND_PLUGINS_TOGGLE"
    PI_SETTINGS_DISABLED_BANNER = "PI_SETTINGS_DISABLED_BANNER"

    # Notes panel
    PANEL_ICON_NOTES = "PANEL_ICON_NOTES"
    NOTES_PANEL = "NOTES_PANEL"
    NOTES_PANEL_EDITOR = "NOTES_PANEL_EDITOR"

    # Chat view mode
    TAB_CONTEXT_MENU_DEBUG_VIEW = "TAB_CONTEXT_MENU_DEBUG_VIEW"
    ALPHA_CHAT_INTRO = "ALPHA_CHAT_INTRO"
    ALPHA_CHAT_VIEW = "ALPHA_CHAT_VIEW"
    ALPHA_CHAT_BOTTOM_SENTINEL = "ALPHA_CHAT_BOTTOM_SENTINEL"
    ALPHA_CHAT_MESSAGE = "ALPHA_CHAT_MESSAGE"
    ALPHA_CHAT_TEXT = "ALPHA_CHAT_TEXT"
    ALPHA_CHAT_TOOL_LINE = "ALPHA_CHAT_TOOL_LINE"
    ALPHA_CHAT_TOOL_NAME = "ALPHA_CHAT_TOOL_NAME"
    ALPHA_JUMP_TO_BOTTOM_BUTTON = "ALPHA_JUMP_TO_BOTTOM_BUTTON"
    ALPHA_JUMP_TO_BOTTOM_WRAPPER = "ALPHA_JUMP_TO_BOTTOM_WRAPPER"
    ALPHA_CHAT_TOOL_GROUP = "ALPHA_CHAT_TOOL_GROUP"
    ALPHA_CHAT_COPY_BUTTON = "ALPHA_CHAT_COPY_BUTTON"
    ALPHA_CHAT_TABLE = "ALPHA_CHAT_TABLE"
    ALPHA_CHAT_TABLE_WRAP_TOGGLE = "ALPHA_CHAT_TABLE_WRAP_TOGGLE"
    ALPHA_CHAT_BLOCKQUOTE = "ALPHA_CHAT_BLOCKQUOTE"
    ALPHA_CHAT_BLOCKQUOTE_COPY = "ALPHA_CHAT_BLOCKQUOTE_COPY"
    SCULPT_SENT_VIA_BADGE = "SCULPT_SENT_VIA_BADGE"
    ALPHA_CHAT_FILE_PATH_LINK = "ALPHA_CHAT_FILE_PATH_LINK"
    ALPHA_CHAT_CHIP_ROW = "ALPHA_CHAT_CHIP_ROW"
    ALPHA_CHAT_FILE_CHIP = "ALPHA_CHAT_FILE_CHIP"
    ALPHA_CHAT_CHIP_POPOVER = "ALPHA_CHAT_CHIP_POPOVER"
    ALPHA_CHAT_CHIP_VIEW_FULL_DIFF_BTN = "ALPHA_CHAT_CHIP_VIEW_FULL_DIFF_BTN"
    ALPHA_CHAT_BASH_BLOCK = "ALPHA_CHAT_BASH_BLOCK"
    ALPHA_CHAT_BASH_OUTPUT = "ALPHA_CHAT_BASH_OUTPUT"
    ALPHA_CHAT_TOOL_PILL_ROW = "ALPHA_CHAT_TOOL_PILL_ROW"
    ALPHA_CHAT_TOOL_PILL = "ALPHA_CHAT_TOOL_PILL"
    ALPHA_CHAT_TOOL_PILL_POPOVER = "ALPHA_CHAT_TOOL_PILL_POPOVER"
    ALPHA_CHAT_SUBAGENT_PILL = "ALPHA_CHAT_SUBAGENT_PILL"
    STREAMING_CURSOR = "STREAMING_CURSOR"
    STATUS_PILL = "STATUS_PILL"
    STATUS_PILL_LABEL = "STATUS_PILL_LABEL"
    STATUS_PILL_ELAPSED = "STATUS_PILL_ELAPSED"
    STATUS_PILL_STOP = "STATUS_PILL_STOP"
    STATUS_PILL_ANIMATION = "STATUS_PILL_ANIMATION"
    TURN_FOOTER = "TURN_FOOTER"
    TURN_FOOTER_TOKEN_COUNT = "TURN_FOOTER_TOKEN_COUNT"
    TURN_FOOTER_FILE_COUNT = "TURN_FOOTER_FILE_COUNT"
    TURN_FOOTER_FILE_ROW = "TURN_FOOTER_FILE_ROW"
    TOKEN_POPOVER = "TOKEN_POPOVER"
    DEBUG_CHAT_VIEW = "DEBUG_CHAT_VIEW"
    DEBUG_CHAT_BLOCK = "DEBUG_CHAT_BLOCK"

    # Workspace Peek
    WORKSPACE_PEEK_POPOVER = "WORKSPACE_PEEK_POPOVER"
    WORKSPACE_PEEK_BANNER = "WORKSPACE_PEEK_BANNER"
    WORKSPACE_PEEK_HEADER = "WORKSPACE_PEEK_HEADER"
    WORKSPACE_PEEK_AGENT_ROW = "WORKSPACE_PEEK_AGENT_ROW"
    WORKSPACE_PEEK_EXPAND = "WORKSPACE_PEEK_EXPAND"
    WORKSPACE_PEEK_FOOTER = "WORKSPACE_PEEK_FOOTER"

    # Workspace metadata bar
    AGENT_STATUS_DOT = "AGENT_STATUS_DOT"
    DIFF_SUMMARY = "DIFF_SUMMARY"

    # Fatal startup error page (rendered by BackendStatusBoundary when the
    # Python backend exits or errors before the UI reaches a running state).
    BACKEND_ERROR_PAGE = "BACKEND_ERROR_PAGE"

    # Shutdown screen states rendered by BackendStatusBoundary while the
    # backend status is "shutting_down". The spinner shows by default; if
    # shutdown does not complete within the stall timeout, the renderer
    # swaps to the stalled-recovery message so the user is not stuck on
    # an indefinite progress bar after a failed auto-update install.
    BACKEND_SHUTDOWN_SPINNER = "BACKEND_SHUTDOWN_SPINNER"
    BACKEND_SHUTDOWN_STALLED = "BACKEND_SHUTDOWN_STALLED"
